# Generated by Django 3.1.3 on 2021-05-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobileProvidersApp', '0002_provider_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='number',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='profilePicture',
            field=models.ImageField(default='default.png', upload_to='profilePicture'),
        ),
        migrations.CreateModel(
            name='Cient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('passportID', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MobileProvidersApp.number')),
            ],
        ),
    ]
