# Generated by Django 3.1.3 on 2021-05-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileProvidersApp', '0003_auto_20210504_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cient',
            new_name='Client',
        ),
    ]
